name: Docker build and push

on:
  push:
    branches:
      - "main"
    paths:
      - "dockerfiles/**"
      - "scripts/**"
  pull_request:
  workflow_dispatch:

jobs:
  build_and_push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 720

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GHCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare editorsupports
        id: prep-editorsupports
        env:
          STAGE: editorsupports
        run: |
          DOCKER_IMAGE="ghcr.io/${{ github.repository }}/${{ env.STAGE }}"
          TAGS="$DOCKER_IMAGE:latest"
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=tags::${TAGS}
          echo ${DOCKER_IMAGE}
          echo ${TAGS}

      - name: Build and push editorsupports
        uses: docker/build-push-action@v2.7.0
        env:
          STAGE: editorsupports
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep-editorsupports.outputs.tags }}
          file: dockerfiles/Dockerfile
          target: ${{ env.STAGE }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R with the R language server
            org.opencontainers.image.title=${{ steps.prep-editorsupports.outputs.image }}
          cache-from: |
            type=registry,ref=${{ steps.prep-editorsupports.outputs.image }}:latest
          cache-to: type=inline

      - name: Prepare tidyverse
        id: prep-tidyverse
        env:
          STAGE: tidyverse
        run: |
          DOCKER_IMAGE="ghcr.io/${{ github.repository }}/${{ env.STAGE }}"
          TAGS="$DOCKER_IMAGE:latest"
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=tags::${TAGS}
          echo ${DOCKER_IMAGE}
          echo ${TAGS}

      - name: Build and push tidyverse
        uses: docker/build-push-action@v2.7.0
        env:
          STAGE: tidyverse
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep-tidyverse.outputs.tags }}
          file: dockerfiles/Dockerfile
          target: ${{ env.STAGE }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R with the tidyverse packages
            org.opencontainers.image.title=${{ steps.prep-tidyverse.outputs.image }}
          cache-from: |
            type=registry,ref=${{ steps.prep-editorsupports.outputs.image }}:latest
            type=registry,ref=${{ steps.prep-tidyverse.outputs.image }}:latest
          cache-to: type=inline
