name: Docker build and push

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "main"
    tags:
      - v*
    paths:
      - "dockerfiles/**"
      - "scripts/**"
      - ".github/workflows/docker-build-push.yml"
      - "buildargs/**"
  pull_request:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    if: "github.actor!= 'dependabot[bot]' && !contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2.3.4
      - id: set-matrix
        run: |
          content=$(jq -r 'tostring' buildargs/versions.json)
          echo "::set-output name=matrix::$content"
          echo $content

  echo_matrix:
    needs: generate_matrix
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.generate_matrix.outputs.matrix }}"
          echo "${{fromJson(needs.generate_matrix.outputs.matrix)}}"

  build_and_push:
    needs: generate_matrix
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 720
    strategy:
      fail-fast: true
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.r_version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.r_version }}-
            ${{ runner.os }}-buildx-

      - name: Login to GHCR
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push builder
        uses: docker/build-push-action@v2.4.0
        env:
          STAGE: builder
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ env.STAGE }}:${{ matrix.r_version }}
          build-args: |
            VARIANT=${{ matrix.r_version }}
            CRAN_URL=${{ matrix.cran }}
          file: dockerfiles/builder.Dockerfile
          target: ${{ env.STAGE }}
          pull: true
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R version ${{ matrix.r_version }}
            org.opencontainers.image.title=${{ github.repository }}/${{ env.STAGE }}:${{ matrix.r_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push r-ver
        uses: docker/build-push-action@v2.4.0
        env:
          STAGE: r-ver
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ matrix.r_version }}
          build-args: |
            VARIANT=${{ matrix.r_version }}
            CRAN_URL=${{ matrix.cran }}
          file: dockerfiles/builder.Dockerfile
          target: ${{ env.STAGE }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R version ${{ matrix.r_version }}
            org.opencontainers.image.title=${{ github.repository }}:${{ matrix.r_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push editorsupports
        uses: docker/build-push-action@v2.4.0
        env:
          STAGE: editorsupports
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ env.STAGE }}:${{ matrix.r_version }}
          build-args: |
            VARIANT=${{ matrix.r_version }}
            CRAN_URL=${{ matrix.cran }}
          file: dockerfiles/builder.Dockerfile
          target: ${{ env.STAGE }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R version ${{ matrix.r_version }}
            org.opencontainers.image.title=${{ github.repository }}/${{ env.STAGE }}:${{ matrix.r_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push tidyverse
        uses: docker/build-push-action@v2.4.0
        env:
          STAGE: tidyverse
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ env.STAGE }}:${{ matrix.r_version }}
          build-args: |
            VARIANT=${{ matrix.r_version }}
            CRAN_URL=${{ matrix.cran }}
          file: dockerfiles/builder.Dockerfile
          target: ${{ env.STAGE }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=A Docker image of R version ${{ matrix.r_version }}
            org.opencontainers.image.title=${{ github.repository }}/${{ env.STAGE }}:${{ matrix.r_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
